### ISSUE TITLE
Chi squared - high value while the data fit to the circuit model

### ISSUE THREAD

**Issue by oriyonet** [j-zimmermann/ImpedanceFitter#11]
Hi,
I tried to implement the package to fit circuit for a simple file I have for impedance measurement of ferro-ferricyanide solution.
I compared the circuit fitting to the one from pstrace software by Palmsens in which I am using.
The fitted circuit is randles with CPE
As seen in the attached files the values are close. However, the chi squared value received using the package is significantly higher although the data fits the circuit.
I was wondering what cause this difference and if there is a way to understand it and maybe edit it .

Thank you,
Oriya.
[fcn_eis_fliped.csv](https://github.com/j-zimmermann/ImpedanceFitter/files/10308367/fcn_eis_fliped.csv)
[fit_result_fcn_eis_fliped.csv0_impedance_overview.pdf](https://github.com/j-zimmermann/ImpedanceFitter/files/10308370
![scheme](https://user-images.githubusercontent.com/56882201/209672963-6e68a0a4-971d-4a20-9774-a815a30de8fe.svg)
/fit_result_fcn_eis_fliped.csv0_impedance_overview.pdf)
[pstrace_fit.xlsx](https://github.com/j-zimmermann/ImpedanceFitter/files/10308371/pstrace_fit.xlsx)

**Comment by j-zimmermann** [comment]
Hi Oriya,

Could you please share the script using ImpedanceFitter with me?
There are some peculiarities regarding the weighting and residual, which might explain the observed behaviour.

Best,
Julius

**Comment by oriyonet** [comment]
Hey Julius,
I appreciate your fast response!
Attached the script and again the data I am trying to fit (I can't attached a py file therefore a txt attached instead).

Thank you!
Oriya.
[impedance_analysis.txt](https://github.com/j-zimmermann/ImpedanceFitter/files/10313649/impedance_analysis.txt)

**Comment by j-zimmermann** [comment]
You're welcome :)

I had a look at your script.
My naive guess is that the definition of chi-sqr is different in pstrace.
LMFIT uses the following definition: https://lmfit.github.io/lmfit-py/fitting.html#lmfit.minimizer.MinimizerResult.chisqr

Because the impedance is often weighted by, for example, its modulus, I decided to stick to this information. pstrace might use the weighted impedance though. You can implement this yourself by playing around with the residual array: https://lmfit.github.io/lmfit-py/fitting.html#lmfit.minimizer.MinimizerResult.residual

Here is a reduced form of your script with comments on the Lin-KK test and a suggestion for the fit at the end
```
import impedancefitter
import pandas

# parameters
CPE_Rct = 100.
CPE_Rs = 20.
CPE_Aw = 300.
k = 0.5
alpha = 0.5

# initialise fitter with verbose output and show fit result
fitter2 = impedancefitter.Fitter('CSV', LogLevel='DEBUG', show=True, fileList=["fcn_eis_fliped.csv"])
model = 'R_s + parallel(R_ct + W, CPE)'

# Julius: adding a capacitance is appropriate here
results, mus, residuals = fitter2.linkk_test(capacitance=True)

# define model and initial guess
parameters = {'ct_R': {'value': 3. * CPE_Rct},
              's_R': {'value': 0.5 * CPE_Rs},
              'Aw': {'value': 1.2 * CPE_Aw},
              'alpha': {'value': 1 * alpha},
              'k': {'value': 0.1 * k}}


fitter2.run(model, parameters=parameters)
fitter2.plot_initial_best_fit()
fit_results = fitter2.model_results

chi = pandas.DataFrame(data=[fit_results.get('fcn_eis_fliped.csv_0').chisqr], columns=['chi squared'])
model_comp = pandas.DataFrame(data=[fit_results.get('fcn_eis_fliped.csv_0').values])
model_comp1 = pandas.DataFrame(data=[fit_results.get('fcn_eis_fliped.csv_0').params])
# try modulus weighting and compute the relative difference w.r.t. the modulus
fitter2.run(model, parameters=parameters, weighting="modulus", residual="absolute", report=True, show=True)
```

**Comment by oriyonet** [comment]
Thank you very much!
The chi-squared now even with my previous code is similar to the one with your modifications.
Regarding the residuals, I see you adjusted it to "absolute" in the run method and I do not completely understand which other options this variable can get (does not appear in the manuals).
Also, I am not sure how can I manipulate the residuals array due to the fact it is received after the LMfit.
Regarding the weighting method I will check this option as well. 

Thank you very much again,
Oriya.

**Comment by j-zimmermann** [comment]
Great, so I will close this issue :)

The option is documented here:
https://impedancefitter.readthedocs.io/en/latest/fitting.html#impedancefitter.fitter.Fitter.run
You can choose between `parts`, `diff` and `absolute`.
This affects only the plot though but not the residual array.
You cannot manipulate it because the residual array is meant to inform you about the quality of the fit.
You can adjust the weights though, which will have an immediate effect on the fitting result.

If you have more detailed questions you can also reach out to me via email.

**Comment by oriyonet** [comment]
Hello Julius,
How are you doing?
I thank you again for your previous response.
I was wondering if there is an option to add new circuit components.
Specifically asking regarding anomalous diffusion elements or bisquert
elements.
Attached a link to one of the relevant papers.
https://www.sciencedirect.com/science/article/pii/S0022072800004976?casa_token=cWeHCcnu984AAAAA:LBf3JqCHbRUYcs3zasm4cLu1fRfZ2tWztCXaotjnHGN0ra5qJRiy0K4wjbAnaIWNsJ_H3ghk
I have seen in the literature data similar to mine fitted with this element
as part of the electrical circuit.

I really appreciate all your help!!
Oriya.

‫בתאריך יום ה׳, 29 בדצמ׳ 2022 ב-13:52 מאת ‪Julius Zimmermann‬‏ <‪
***@***.***‬‏>:‬

**Comment by j-zimmermann** [comment]
Hi Oriya,

Would you mind continuing our conversation via email?
You can reach me via julius.zimmermann@uni-rostock.de
I have already implemented some diffusion models (https://impedancefitter.readthedocs.io/en/latest/elements.html#impedancefitter.elements.Z_wo), so I do not think that it would be a big problem to add more elements.

Best,
Julius

Best,
Julius
